USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_checkquyenxoanhanvien]    Script Date: 11/17/2021 06:27:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_checkquyenxoanhanvien] 
@TENLOGIN VARCHAR(50),	--TENLOGIN LÀ TRUYỀN MÃ NHÂN VIÊN VÔ
@ROLENGUOIXOA VARCHAR(50)
AS
BEGIN
DECLARE @SID VARBINARY(85)
	SELECT @SID = SID FROM SYS.SYSUSERS WHERE NAME = @TENLOGIN
	IF (@SID IS NOT NULL)
	BEGIN
		DECLARE @LGNAME VARCHAR(50)
		SELECT @LGNAME = LOGINNAME FROM SYS.SYSLOGINS WHERE SID = @SID
	END
DECLARE @TENUSER NVARCHAR(50), @USERID INT, @ROLE NVARCHAR(50)
	
	SELECT @USERID= UID ,@TENUSER=NAME FROM SYS.SYSUSERS WHERE SID = SUSER_SID(@LGNAME)
IF EXISTS(SELECT HO+ ' '+ TEN FROM DBO.NHANVIEN WHERE MANV = @TENUSER AND TRANGTHAIXOA=0)
BEGIN
	SELECT 
   @ROLE = NAME
   FROM SYS.SYSUSERS 
   WHERE UID = (SELECT GROUPUID 
                 FROM SYS.SYSMEMBERS 
                   WHERE MEMBERUID= @USERID
               )

END
IF((@ROLENGUOIXOA = 'CHINHANH' AND @ROLE = 'CONGTY')OR(@ROLENGUOIXOA = 'USER' AND @ROLE = 'CONGTY') OR(@ROLENGUOIXOA = 'USER' AND @ROLE = 'CHINHANH'))
RAISERROR('BẠN KHÔNG ĐỦ QUYỀN ĐỂ XÓA NHÂN VIÊN NÀY',16,1)
END

GO

