USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_capnhatsoluongton]    Script Date: 11/17/2021 06:27:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_capnhatsoluongton] @MAVT NCHAR(4), 
@SOLUONG INT,
@LOAI CHAR(1)
AS
BEGIN
DECLARE  @SL INT	
IF EXISTS (SELECT  MAVT FROM VATTU WHERE MAVT= @MAVT)
BEGIN
	SELECT @SL= SOLUONGTON FROM VATTU WHERE MAVT= @MAVT
	IF @LOAI ='N'
		BEGIN
		UPDATE VATTU SET SOLUONGTON = @SL+ @SOLUONG WHERE MAVT= @MAVT
		END
	ELSE 
		BEGIN
		IF @SL - @SOLUONG >=0
		UPDATE VATTU SET SOLUONGTON = @SL - @SOLUONG WHERE MAVT= @MAVT
		ELSE
		RAISERROR(N'SỐ LƯỢNG VẬT TƯ KHÔNG ĐỦ',16,1)
		END
END
ELSE
    RAISERROR(N'VẬT TƯ KHÔNG TỒN TẠI',16,1)
END	
GO

