USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_chuyenchinhanh]    Script Date: 11/17/2021 06:27:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_chuyenchinhanh] 
@MANV INT,
@MAMOI INT
AS

SET XACT_ABORT ON;
BEGIN TRY
BEGIN DISTRIBUTED TRANSACTION;
	DECLARE @TTX INT
	SELECT @TTX=TRANGTHAIXOA FROM NHANVIEN WHERE MANV = @MANV
	IF(@TTX=0)
		BEGIN
			DECLARE @MACN NCHAR(10)
			SELECT @MACN = MACN FROM LINK1.QLVT_DATHANG.DBO.CHINHANH

			-- KIEM TRA NHAN VIEN DA TON TAI O CHI NHANH CON LAI CHUA
			DECLARE @HO NVARCHAR(50), @TEN NVARCHAR(50) , @NGAYSINH NVARCHAR(50), @DIACHI NVARCHAR(50)
			SELECT @HO= HO, @TEN=TEN, @DIACHI=DIACHI,@NGAYSINH= NGAYSINH FROM NHANVIEN WHERE MANV=@MANV
			SELECT @@ROWCOUNT FROM LINK1.QLVT_DATHANG.DBO.NHANVIEN 
					WHERE (HO= @HO AND TEN= @TEN AND DIACHI= @DIACHI AND NGAYSINH= @NGAYSINH)

			IF(@@ROWCOUNT = 1 )-- NEU NHAN VIEN DA TON TAI Ở CHI NHANH CON LAI
				BEGIN
					UPDATE LINK1.QLVT_DATHANG.DBO.NHANVIEN SET TRANGTHAIXOA = 0
					WHERE HO = @HO AND TEN = @TEN AND NGAYSINH= @NGAYSINH AND DIACHI= @DIACHI
				END
			ELSE
				BEGIN
					INSERT INTO LINK1.QLVT_DATHANG.DBO.NHANVIEN (MANV, HO, TEN, DIACHI, NGAYSINH, LUONG, MACN, TRANGTHAIXOA)
					SELECT MANV=@MAMOI,HO,TEN,DIACHI,NGAYSINH,LUONG,MACN=@MACN,TRANGTHAIXOA = 0
					FROM NHANVIEN
					WHERE MANV = @MANV
				END
				-- CẬP NHẬP TRẠNG THÁI XOÁ CỦA NHÂN VIÊN HIỆN TẠI
			UPDATE NHANVIEN SET TRANGTHAIXOA = 1
			WHERE MANV = @MANV
		END
	ELSE
		RAISERROR(50001, 18, 1, N'NHÂN VIÊN ĐÃ CHUYỂN CHI NHÁNH')
COMMIT TRANSACTION;

END TRY
-- bắt trường hợp nếu đã có trasaction mở rồi mà mở thêm
BEGIN CATCH
	--@@TRANCOUNT trả về số lượng transaction đang hoạt động
	IF (@@TRANCOUNT > 0)
	BEGIN
		ROLLBACK TRAN;
	END;
	THROW;
END CATCH

GO

