USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_dsnvcohoadon]    Script Date: 11/17/2021 06:28:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_dsnvcohoadon]
AS
BEGIN
SELECT DISTINCT NV.MANV, NV.HO + ' ' + NV.TEN AS HOTEN
FROM  NHANVIEN AS NV, PHIEUNHAP AS PN  , PHIEUXUAT AS PX
WHERE NV.MANV = PN.MANV OR  NV.MANV = PX.MANV
END

GO

