USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_hdnv]    Script Date: 12/13/2021 04:19:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_hdnv]
@MANV INT,
@BEGIN NCHAR(10),
@END NCHAR(10)
AS
BEGIN
SET NOCOUNT ON;-- không trả về số lượng hàng bị ảnh hưởng
	IF 1=0 BEGIN 
	SET FMTONLY OFF --FMTONLY được sử dụng để lấy danh sách tên cột và kiểu dữ liệu
	END

  -- PHIEU NHAP
    SELECT FORMAT(PN_NV.NGAY,'MM/yyyy') AS THANGNAM,
		SUBSTRING(CONVERT(VARCHAR, PN_NV.NGAY, 103),0,11) AS NGAY,
		PN_NV.MAPN , PN_NV.HOTENKH , VT.TENVT , 
		TENKHO ,SOLUONG ,
		DONGIA , SOLUONG * DONGIA AS TRIGIA,
		MANV , HOTENNV  into #phieuNhap
	FROM (
			SELECT MAPN, NGAY, HOTENKH = '',
			TENKHO = (SELECT TENKHO FROM KHO WHERE KHO.MAKHO = PN.MAKHO),
			NV.MANV, HO+ ' '+TEN AS HOTENNV  
			FROM (SELECT MAPN, NGAY, MANV, MAKHO FROM DBO.PHIEUNHAP WITH (INDEX = IX_NGAYPN) WHERE NGAY BETWEEN @BEGIN AND @END  ) PN ,(SELECT MANV, HO, TEN FROM NHANVIEN ) AS NV
			WHERE NV.MANV = @MANV AND  PN.MANV= NV.MANV 
		 ) PN_NV, CTPN,(SELECT TENVT, MAVT FROM VATTU) VT
	WHERE CTPN.MAPN = PN_NV.MAPN AND VT.MAVT = CTPN.MAVT   
	ORDER BY THANGNAM, NGAY

	-- PHIEU XUAT
      SELECT FORMAT(PX_NV.NGAY,'MM/yyyy') AS THANGNAM,
	    SUBSTRING(CONVERT(VARCHAR, PX_NV.NGAY, 103),0,11) AS NGAY ,
		PX_NV.MAPX , HOTENKH , VT.TENVT , 
		TENKHO ,SOLUONG ,
		DONGIA , SOLUONG * DONGIA AS TRIGIA,
		MANV , HOTENNV into #phieuXuat
		FROM (
			SELECT MAPX, NGAY, HOTENKH,
			TENKHO = (SELECT TENKHO FROM KHO WHERE KHO.MAKHO = PX.MAKHO),
			NV.MANV, NV.HO+ ' '+NV.TEN AS HOTENNV  
			FROM(SELECT MAPX, NGAY, HOTENKH, MANV, MAKHO FROM DBO.PhieuXuat WITH (INDEX = IX_NGAYPX) WHERE NGAY BETWEEN @BEGIN AND @END  )PX ,(SELECT MANV, HO, TEN FROM NHANVIEN ) AS NV
			WHERE NV.MANV = @MANV AND  PX.MANV= NV.MANV 
		 ) PX_NV, CTPX,(SELECT TENVT, MAVT FROM VATTU) VT
	WHERE CTPX.MAPX = PX_NV.MAPX AND VT.MAVT = CTPX.MAVT  
	ORDER BY THANGNAM, NGAY

-- GOP
	SELECT N.THANGNAM ,  N.NGAY, N.MAPN , N.HOTENKH, N.TENVT  , N.TENKHO , N.SOLUONG , N.DONGIA  ,N.TRIGIA , N.MANV , N.HOTENNV 
	FROM #phieuNhap N
	UNION
	SELECT X.THANGNAM ,X.NGAY, X.MAPX, X.HOTENKH , X.TENVT  , X.TENKHO , X.SOLUONG  , X.DONGIA  , X.TRIGIA , X.MANV, X.HOTENNV 
	FROM #phieuXuat X
END

GO

