USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_ktrasoluongvattu]    Script Date: 11/17/2021 06:30:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE proc [dbo].[sp_ktrasoluongvattu]
@MAPHIEU NCHAR(8),
@MAVT NCHAR(4),
@SOLUONG INT
AS
BEGIN
IF(@SOLUONG<=(SELECT SOLUONG FROM CTDDH WHERE MASODDH= @MAPHIEU AND MAVT= @MAVT))
		--SELECT SOLUONG FROM CTDDH WHERE MASODDH= @MAPHIEU AND MAVT= @MAVT
		return 1;
ELSE
	RAISERROR(N'SỐ LƯỢNG VẬT TƯ KHÔNG HỢP LỆ !',16,1)
END

GO

