USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_layquyennhanvien]    Script Date: 12/13/2021 03:38:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE proc [dbo].[sp_layquyennhanvien]
@TENLOGIN VARCHAR(50)
AS
BEGIN
DECLARE @USERID INT, @ROLE NVARCHAR(50) 
SELECT @USERID = UID FROM SYS.SYSUSERS WHERE NAME = @TENLOGIN
IF EXISTS(SELECT HO+ ' '+ TEN FROM DBO.NHANVIEN WHERE MANV = @TENLOGIN AND TRANGTHAIXOA=0)
BEGIN
	SELECT 
   @ROLE = NAME
   FROM SYS.SYSUSERS 
   WHERE UID = (SELECT GROUPUID 
                 FROM SYS.SYSMEMBERS 
                 WHERE MEMBERUID= @USERID
                )
IF(@ROLE IS NOT NULL)
	BEGIN
	SELECT @ROLE
	END
ELSE
	RAISERROR('NHÂN VIÊN KHÔNG CÓ QUYỀN',16,1)
END
END
GO

