USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_phieunvlaptrongnamtheoloai]    Script Date: 11/17/2021 06:30:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_phieunvlaptrongnamtheoloai]
@MANV INT, @LOAI CHAR, @NAM INT
AS
BEGIN
IF  @LOAI='N'
	SELECT PS.PHIEU, NGAY, TENVT, SOLUONG,DONGIA
	FROM (SELECT MAPN AS PHIEU ,NGAY FROM PHIEUNHAP
			WHERE MANV= @MANV AND YEAR(NGAY)= @NAM) PS, CTPN CT, VATTU VT
	WHERE PS.PHIEU= CT.MAPN AND CT.MAVT= VT.MAVT
	ORDER BY NGAY, PS.PHIEU
ELSE
	SELECT PS.PHIEU, NGAY, TENVT, SOLUONG,DONGIA
	FROM (SELECT MAPX AS PHIEU ,NGAY FROM PHIEUXUAT
			WHERE MANV= @MANV AND YEAR(NGAY)= @NAM) PS, CTPX CT, VATTU VT
	WHERE PS.PHIEU= CT.MAPX AND CT.MAVT= VT.MAVT
	ORDER BY NGAY, PS.PHIEU
 END

GO

