USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_timtenkho]    Script Date: 12/14/2021 12:16:35 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_timtenkho]
@TENKHO NVARCHAR(30)
AS
BEGIN
	IF EXISTS (SELECT TENKHO FROM LINK2.QLVT_DATHANG.DBO.KHO WHERE TENKHO = @TENKHO)
		RETURN 1;
	ELSE
		RAISERROR(N'TEN KHO BẠN TÌM KHÔNG TỒN TẠI',16,1)
END
GO

