USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_themctddh_ctpn]    Script Date: 11/20/2021 04:35:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_themctddh_ctpn]
@PN NCHAR(8)
AS
BEGIN
	SET NOCOUNT ON;
    SELECT PN.MAPN, CT.MAVT, CT.SOLUONG, CT.DONGIA INTO #CTP
    FROM PHIEUNHAP PN, CTDDH CT 
    WHERE PN.MASODDH= CT.MASODDH AND PN.MAPN= @PN
	


	INSERT CTPN(MAPN, MAVT,SOLUONG,DONGIA)
    SELECT MAPN, MAVT,SOLUONG,DONGIA FROM #CTP;
END
GO

