USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_timphieunhap]    Script Date: 11/17/2021 06:32:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[sp_timphieunhap]
@MAPN NCHAR(8)
AS
BEGIN
	IF EXISTS (SELECT MAPN FROM DBO.PHIEUNHAP WHERE MAPN = @MAPN)
		RETURN 1;
	ELSE
		IF EXISTS (SELECT MAPN FROM LINK1.QLVT_DATHANG.DBO.PHIEUNHAP WHERE MAPN = @MAPN)
			RETURN 1;
		ELSE
			RAISERROR(N'PHIẾU NHẬP BẠN TÌM KHÔNG TỒN TẠI',16,1)
END

GO

