USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_timctddh]    Script Date: 11/17/2021 06:31:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_timctddh]
@MADDH NCHAR(8),
@MAVT NCHAR(4)
AS
BEGIN
	IF EXISTS (SELECT * FROM DBO.CTDDH WHERE MASODDH = @MADDH AND MAVT = @MAVT)
		RETURN 1;
	ELSE
		IF EXISTS (SELECT * FROM LINK1.QLVT_DATHANG.DBO.CTDDH WHERE MASODDH = @MADDH AND MAVT = @MAVT)
			RETURN 1;
		ELSE
			RAISERROR(N'CHI TIẾT ĐƠN ĐẶT HÀNG BẠN TÌM KHÔNG TỒN TẠI',16,1)
END

GO

