USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_tontainhanvien]    Script Date: 11/21/2021 09:07:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_tontainhanvien] @HO NVARCHAR(40), @TEN NVARCHAR(10),
@DIACHI NVARCHAR(100),@NGAYSINH NVARCHAR(50)
AS
BEGIN
	IF EXISTS (SELECT MANV FROM NHANVIEN WHERE HO= @HO AND TEN= @TEN AND NGAYSINH= @NGAYSINH AND DIACHI= @DIACHI )
			RETURN 1;
	ELSE
		IF EXISTS (SELECT MANV FROM LINK1.QLVT_DATHANG.DBO.NHANVIEN WHERE HO= @HO AND TEN= @TEN AND NGAYSINH= @NGAYSINH AND DIACHI= @DIACHI )
			RETURN 1;
		ELSE
			RAISERROR(N'NHAN VIEN BẠN TÌM KHÔNG TỒN TẠI',16,1)
END
GO

