USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_tonghopnhapxuat]    Script Date: 12/13/2021 01:02:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE proc [dbo].[sp_tonghopnhapxuat]
@BEGIN NCHAR(10),
@END NCHAR(10),
@MODE NCHAR
AS
BEGIN
	IF(@MODE = 'K')	--QUYỀN CHI NHÁNH
	BEGIN
		SELECT NGAY= ISNULL(TOHOPXUAT.NGAY, TOHOPNHAP.NGAY), TONGTIENNHAP=ISNULL(TOHOPNHAP.TONGTIEN,0),
				TONGTIENXUAT=ISNULL(TOHOPXUAT.TONGTIEN,0), TYLENHAP=(ISNULL(TOHOPNHAP.TONGTIEN,0)/(ISNULL(TOHOPNHAP.TONGTIEN,0)+ISNULL(TOHOPXUAT.TONGTIEN,0))),
				TYLEXUAT=(ISNULL(TOHOPXUAT.TONGTIEN,0)/(ISNULL(TOHOPNHAP.TONGTIEN,0)+ISNULL(TOHOPXUAT.TONGTIEN,0)))
		FROM
		(
			(
				SELECT PXFILTER.NGAY, ISNULL(SUM(CTPX.SOLUONG * CTPX.DONGIA),0) AS 'TONGTIEN'
				FROM (SELECT MAPX, NGAY FROM DBO.PHIEUXUAT WHERE NGAY BETWEEN @BEGIN AND @END) PXFILTER
				INNER JOIN DBO.CTPX CTPX ON CTPX.MAPX = PXFILTER.MAPX
				GROUP BY PXFILTER.NGAY
			) TOHOPXUAT
			 FULL OUTER JOIN
			(
				SELECT PNFILTER.NGAY, ISNULL(SUM(CTPN.SOLUONG * CTPN.DONGIA),0) AS 'TONGTIEN'
				FROM (SELECT MAPN, NGAY FROM DBO.PHIEUNHAP WHERE NGAY BETWEEN @BEGIN AND  @END) PNFILTER
				INNER JOIN DBO.CTPN CTPN ON CTPN.MAPN = PNFILTER.MAPN
				GROUP BY PNFILTER.NGAY
			) TOHOPNHAP
			ON TOHOPXUAT.NGAY = TOHOPNHAP.NGAY
		)
	END
	ELSE
	BEGIN
		SELECT NGAY= ISNULL(TOHOPXUAT.NGAY, TOHOPNHAP.NGAY), TONGTIENNHAP=ISNULL(TOHOPNHAP.TONGTIEN,0),
				TONGTIENXUAT=ISNULL(TOHOPXUAT.TONGTIEN,0), TYLENHAP=(ISNULL(TOHOPNHAP.TONGTIEN,0)/(ISNULL(TOHOPNHAP.TONGTIEN,0)+ISNULL(TOHOPXUAT.TONGTIEN,0))),
				TYLEXUAT=(ISNULL(TOHOPXUAT.TONGTIEN,0)/(ISNULL(TOHOPNHAP.TONGTIEN,0)+ISNULL(TOHOPXUAT.TONGTIEN,0)))
		FROM
		(
			(SELECT PXFILTER.NGAY, ISNULL(SUM(CTPX.SOLUONG * CTPX.DONGIA),0) AS 'TONGTIEN'
			FROM (SELECT MAPX, NGAY FROM LINK0.QLVT_DATHANG.DBO.PHIEUXUAT WHERE NGAY BETWEEN @BEGIN AND @END) PXFILTER
			INNER JOIN LINK0.QLVT_DATHANG.DBO.CTPX CTPX ON CTPX.MAPX = PXFILTER.MAPX
			GROUP BY PXFILTER.NGAY) TOHOPXUAT
			 FULL OUTER JOIN
			(SELECT PNFILTER.NGAY, ISNULL(SUM(CTPN.SOLUONG * CTPN.DONGIA),0) AS 'TONGTIEN'
			FROM (SELECT MAPN, NGAY FROM LINK0.QLVT_DATHANG.DBO.PHIEUNHAP WHERE NGAY BETWEEN @BEGIN AND @END) PNFILTER
			INNER JOIN LINK0.QLVT_DATHANG.DBO.CTPN CTPN ON CTPN.MAPN = PNFILTER.MAPN
			GROUP BY PNFILTER.NGAY) TOHOPNHAP
			ON TOHOPXUAT.NGAY = TOHOPNHAP.NGAY
		)
	END
END
GO

