USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_timkho]    Script Date: 11/17/2021 06:31:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_timkho]
@MAKHO NCHAR(4)
AS
BEGIN
	IF EXISTS (SELECT MAKHO FROM DBO.KHO WHERE MAKHO = @MAKHO)
		RETURN 1;
	ELSE
		IF EXISTS (SELECT MAKHO FROM LINK1.QLVT_DATHANG.DBO.KHO WHERE MAKHO = @MAKHO)
			RETURN 1;
		ELSE
			RAISERROR(N'KHO BẠN TÌM KHÔNG TỒN TẠI',16,1)
END

GO

