USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_timphieuxuat]    Script Date: 11/17/2021 06:32:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_timphieuxuat]
@MAPX NCHAR(8)
AS
BEGIN
IF EXISTS (SELECT MAPX FROM DBO.PHIEUXUAT WHERE MAPX = @MAPX)
		RETURN 1;
	ELSE
		IF EXISTS (SELECT MAPX FROM LINK1.QLVT_DATHANG.DBO.PHIEUXUAT WHERE MAPX = @MAPX)
			RETURN 1;
		ELSE
			RAISERROR(N'PHIEU XUAT BẠN TÌM KHÔNG TỒN TẠI',16,1) 
END

GO

