USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_TAOTAIKHOAN]    Script Date: 11/17/2021 06:31:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_TAOTAIKHOAN] @LGNAME VARCHAR(50),
	@PASS VARCHAR(50),
	@USERNAME VARCHAR(50),
	@ROLE VARCHAR(50)
AS
BEGIN
DECLARE @RET INT
  EXEC @RET= SP_ADDLOGIN @LGNAME, @PASS, 'QLVT_DATHANG'
  IF (@RET =1)  -- LOGIN NAME BI TRUNG
  BEGIN
     RAISERROR ('LOGIN NAME ĐÃ TỒN TẠI', 16,1)
	 RETURN
  END 
  EXEC @RET= SP_GRANTDBACCESS @LGNAME, @USERNAME
  IF (@RET =1)  -- USER  NAME BI TRUNG
  BEGIN
       EXEC SP_DROPLOGIN @LGNAME
       RAISERROR ('USERNAME ĐÃ TỒN TẠI', 16,2)
       RETURN
  END
  EXEC SP_ADDROLEMEMBER @ROLE, @USERNAME
  IF  @ROLE='CONGTY' OR @ROLE='CHINHANH'
  BEGIN
      EXEC SP_ADDSRVROLEMEMBER @LGNAME, 'SECURITYADMIN'   
  END
END

GO

