USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_timddh]    Script Date: 11/17/2021 06:31:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_timddh]
@MADDH NCHAR(8)
AS
BEGIN
	IF EXISTS (SELECT MaSoDDH FROM DBO.DATHANG WHERE MASODDH = @MADDH)
		RETURN 1;
	ELSE
		IF EXISTS (SELECT MasoDDH FROM LINK1.QLVT_DATHANG.DBO.DATHANG WHERE MASODDH = @MADDH)
			RETURN 1;
		ELSE
			RAISERROR(N'ĐƠN ĐẶT HÀNG BẠN TÌM KHÔNG TỒN TẠI',16,1)
END

GO

