USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_undochuyencn]    Script Date: 11/17/2021 06:32:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE proc [dbo].[sp_undochuyencn]
@MANV INT,
@MAMOI INT
AS
SET XACT_ABORT ON 
BEGIN TRANSACTION
BEGIN TRY
	UPDATE NHANVIEN SET TRANGTHAIXOA = 0 WHERE MANV = @MANV
	DELETE LINK1.QLVT_DATHANG.DBO.NHANVIEN WHERE MANV = @MAMOI
	COMMIT
END TRY
BEGIN CATCH
   ROLLBACK
	DECLARE @ErrorMessage VARCHAR(2000)
	SELECT @ErrorMessage = 'Lỗi: ' + ERROR_MESSAGE()
	RAISERROR( @ErrorMessage, 16, 1)
END CATCH

GO

