USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_undothemCTPN]    Script Date: 11/20/2021 04:36:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_undothemCTPN]
@MAPN nchar(8), @MAVT NCHAR(4),@SOLUONG INT,  @LOAI CHAR(1)
AS
SET XACT_ABORT ON 
BEGIN TRANSACTION
BEGIN TRY
	DECLARE @SOLUONG1 INT, @DONGIA INT
	SELECT  @SOLUONG1= SOLUONG,@DONGIA=DONGIA  FROM CTDDH , PhieuNhap PN WHERE CTDDH.MAVT= @MAVT AND  PN.MAPN= @MAPN AND PN.MasoDDH= CTDDH.MasoDDH 
	UPDATE CTPN SET SOLUONG= @SOLUONG1, DONGIA= @DONGIA WHERE  CTPN.MAPN= @MAPN AND CTPN.MAVT= @MAVT
	
	EXEC sp_capnhatsoluongton @MAVT, @SOlUONG, @LOAI
COMMIT TRANSACTION
END TRY
BEGIN CATCH
   ROLLBACK
	DECLARE @ErrorMessage VARCHAR(2000)
	SELECT @ErrorMessage = 'Lỗi: ' + ERROR_MESSAGE()
	RAISERROR( @ErrorMessage, 16, 1)
END CATCH
GO

