USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_undothemPN]    Script Date: 12/13/2021 03:45:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_undothemPN]
@MAPN nchar(8)
AS
SET XACT_ABORT ON 
BEGIN TRANSACTION
BEGIN TRY
	DELETE FROM CTPN WHERE MAPN= @MAPN 
	DELETE FROM PhieuNhap WHERE MAPN= @MAPN
COMMIT TRANSACTION
END TRY
BEGIN CATCH
   ROLLBACK
	DECLARE @ERRORMESSAGE VARCHAR(2000)
	SELECT @ERRORMESSAGE = 'LỖI: ' + ERROR_MESSAGE()
	RAISERROR( @ERRORMESSAGE, 16, 1)
END CATCH
GO

