USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_xoatkdangnhap]    Script Date: 11/17/2021 06:34:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_xoatkdangnhap] 
@TENLOGIN VARCHAR(50)	--TENLOGIN LÀ TRUYỀN MÃ NHÂN VIÊN 
AS
BEGIN

	DECLARE @SID VARBINARY(85)
	SELECT @SID = SID FROM SYS.SYSUSERS WHERE NAME = @TENLOGIN
	IF (@SID IS NULL)
		RAISERROR('NHÂN VIÊN CHƯA TẠO TÀI KHOẢN',16,1)
	ELSE
	BEGIN
		DECLARE @LGNAME VARCHAR(50)
		SELECT @LGNAME = LOGINNAME FROM SYS.SYSLOGINS WHERE SID = @SID
		IF(@LGNAME IS NOT NULL)
		BEGIN
			EXEC SP_DROPUSER @TENLOGIN	--XÓA USER TRONG SERVER ROLE
			EXEC SP_DROPLOGIN @LGNAME	--XÓA TÀI KHOẢN ĐĂNG NHẬP CỦA NHÂN VIÊN
		END
		ELSE
			RAISERROR('NHÂN VIÊN CHƯA TẠO TÀI KHOẢN',16,1)
	END

END 

GO

